= Arquillian Native Platforms support

Support for running native code by Arquillian

== Making it part of your extension

In your project, import following artifact:

[source,xml]
----
<dependency>
    <groupId>org.arquillian.native</artifactId>
    <artifactId>arquillian-native-platform</artifactId>
    <version>${version.arquillian.native.platform}</version>
</dependency>
----

In your extension, inject instance of +ProcessExecutor+. This instance is created in +ArquillianDescriptor+ event and you can observe
+ProcessExecutorCreated+ event if you will. The instance is singleton, so you will always retrieve the same instance.

[source,java]
----
@Instance<ProcessExecutor> processExecutor;
----

== How to use the extension

=== ProcessExecutor

ProcessExecutor allows your extension to execute any code, either external or internal. You have following possibilities:

Execution::
    Use +execute(...)+ method if you want to execute a command and wait for it to be finished
Spawning::
    Use +spawn(...)+ method if you want to execute a command as a daemon in different thread
One time action::
    Use +submit(...)+ method if you want to asynchronously execute a code block
Periodical action::
    Use +scheduleUntilTrue(...)+ method if you want to re-execute code block until condition is fulfilled

=== ProcessExecutor in your test

You can inject +ProcessExecutor+ into test as an +ArquillianResource+ like this:

[source, java]
----
@ArquillianResource ProcessExecutor executor;
----

After this, you can use process executor in your test methods in order to perform platform specific operations. You are free to inject 
this resource into test method itself as well.

== TODO

Currently missing features:

* support to get platform dependent bits automatically
* provide metadata format to simplify platform dependent execution
* create Command abstraction

